baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'example deepin community'
theme = 'up-business-theme'

[params]
    title = "Example deepin community site"
    logo = ""

  [params.social]
    twitter = "linux_deepin"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Download"
    url = "https://www.deepin.org/download/"
    weight = 2

[[menu.main]]
    name = "Blog"
    url = "/blog"
    weight = 3

[[menu.footer]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.friends]]
    name = "deepin"
    url = "https://www.deepin.org"
    weight = 1